### ISSUE TITLE
iOS 11 not supported?

### ISSUE THREAD

**Issue by DanBennettUK** [devbobo/homebridge-flic#10]
The Flic button appears as "Not Supported" on iOS 11. Unsure if it's specific to iOS 11 or there is an issue elsewhere.

Anyone had any luck?

**Comment by DanBennettUK** [comment]
Homebridge has been updated to support iOS 11. Flic is still not supported sadly.

**Comment by dinmammas** [comment]
Hi there.

I'm on iOS11/tvOS11 I have no trouble using this plugin. 

Where are you seeing the message "Not supported"?
