### ISSUE TITLE
The flic button appears to be "incompatible" with iOS 10 "Home" app

### ISSUE THREAD

**Issue by diegopamio** [devbobo/homebridge-flic#2]
It says it is not compatible (though it recognizes it). Shall it be identified as something else?

**Comment by devbobo** [comment]
G'day Diego,

yes, unfortunately, the new official `Home` app currently doesn't support all the different services and characteristics that HomeKit support officially. Hopefully, it will be expanded in the future, however, this doesn't prevent the use of flic buttons with iOS10. There are plenty of other apps that support the services/characteristics that this plugin uses.

Cheers,

David
