### ISSUE TITLE
Mac OS installation

### ISSUE THREAD

**Issue by kapps7** [devbobo/homebridge-flic#8]
Is this supported on macOS. The dependency of flic sdk has thrown me. Thanks.

**Comment by devbobo** [comment]
@kapps7 you could try this... https://github.com/50ButtonsEach/flic-service-osx

**Comment by kapps7** [comment]
Thanks devbobo I have followed the instructions there. I think where I am puzzled, is how do I pair the flic to the mac after running the service. There is no gui or other instruction that I found

**Comment by devbobo** [comment]
@kapps7 Flic provide a command line utility called `simpleclient` in there Linux SDK or you can use an iOS app called Herperus. I've add a wiki article on how to use that app to add buttons...

https://github.com/devbobo/homebridge-flic/wiki/Adding-a-new-Flic-button-to-Homebridge

**Comment by kapps7** [comment]
Thanks. I am trying to use the app. I am getting this error when the scanning strarts:
```
Controller [localhost:5555] - Scanner added
[4/27/2017, 1:14:56 PM] [Flic] Controller [localhost:5555] - Error: Error: This socket has been ended by the other party
```

**Comment by devbobo** [comment]
@kapps7 is your flic-service-osx running on port 5555 or 5551 ? I think it's default is 5551.

**Comment by devbobo** [comment]
@kapps7 i've just tested this on my mac and it seems to be working correctly..

```
[4/27/2017, 1:35:13 PM] Homebridge is running on port 51826.
[4/27/2017, 1:35:13 PM] [Flic] Controller [localhost:5551] - Connected
[4/27/2017, 1:42:03 PM] [Flic] Controller [localhost:5551] - Scanner added
[4/27/2017, 1:42:13 PM] [Flic] Found a public button. Now connecting...
[4/27/2017, 1:42:17 PM] [Flic] Found: Flic 704f7d (80e4da704f7d)
[4/27/2017, 1:42:20 PM] [Flic] 80:e4:da:70:4f:7d - ButtonSingleClick
```

**Comment by kapps7** [comment]
@devbobo Thanks mate, appreciate your help in finally getting this sorted.

I had run in on 5555 when I was troubleshooting previously & I had reexecuted it on the default port but forgot it to change the json - blonde moment ;)

Anyway a bit hit and miss during the scanning process but it is registered and working. 
As far as accessory behaviour is concerned, is this correct:

**ConfigurationL Single click: TV On**

If I single click when the tv is off, the tv is turned on.
If I single click when the tv is already on, then nothing happens so I have to map a different button to turn the tv off. The TV accessory is not a toggle but a direct network command.

**Comment by devbobo** [comment]
@kapps7 awesome, glad you got it working, yeah unfortunately the registration process is a bit hit and miss...I haven't had a lot of time to debug it but i think it might be down to the flic code i'm using.

From the comments about configuration, I'm assuming you are assigning functions on this screen ?

![](https://cloud.githubusercontent.com/assets/680871/25468199/882a1a68-2b57-11e7-8be4-b304246bf57b.jpg)

That functionality only became available recently...but that's not what I use. I use a combination of triggers and scenes to toggle stuff on/off.

For example, I have a pendant light in my lounge, so I create one scene to turn on the pendant and one scene to turn it off...

![](https://cloud.githubusercontent.com/assets/680871/25468390/d700f476-2b58-11e7-8a3f-58123f8e4792.jpg)

I then create to two rules that look for an input from the button and check the current state of the light...

![img_0306](https://cloud.githubusercontent.com/assets/680871/25468392/d8edd70e-2b58-11e7-8181-ca350c3874f4.jpg)

![img_0307](https://cloud.githubusercontent.com/assets/680871/25468394/dbe1eedc-2b58-11e7-87d7-0ee484d6b0ee.jpg)

Note: I don't use the official Apple Home app for this, something like Eve should do the trick as I find the automation setup way easier.

Hope this helps.

**Comment by kapps7** [comment]
Ah I see, so by you using that app you can effectively poll the current state of the device and therefore manipulate the behaviour to your likin... cool

I am trying to minimise using multiple apps and bridges but I know that the HomeKit app has limitation with rules. I want to wait for the WWDC incase these open up before exploring these options.
For example, I would prefer to do what you have done within the json. Not sure if that is possible but atlesat we are or on our way with it now....
Thanks

**Comment by devbobo** [comment]
I should mention that setting up the automation in a 3rd party HomeKit app doesn't require you to then use that app continuously. Once the automation is configured, it's all handled by HomeKit.

The main issue is that the Apple Home app is relatively new in relation to HomeKit itself...and it's really only scratching the surface of what HomeKit can do. Hence the reason for suggesting a 3rd party app...and the fact that I find the Home app's automation configuration interface extremely confusing to work out.

As for doing this stuff in json, I don't see that happening...but I guess you never know.

**Comment by kapps7** [comment]
Yep Agree. Well lets see what the next stage holds for the Home app next month. Thanks again David.
